cws2/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from cws2.views.auth import CreateAccountView, LoginView, LogoutView
from cws2.views.board import IndexBoardView, NewBoardView, ShowBoardView
from cws2.views.dictionary import EditWordView, IndexWordView, NewWordView, ShowWordView
from cws2.views.group import EditGroupView, IndexGroupView, NewGroupView, ShowGroupView
from cws2.views.index import DashboardView
from cws2.views.language import (
    EditLanguageView,
    IndexLanguageView,
    NewLanguageView,
    ShowLanguageView,
)
from cws2.views.message import IndexMessageView
from cws2.views.static import AboutView, ContactView, DonateView, PrivacyView
from cws2.views.translation import (
    IndexTranslationTemplateView,
    NewTranslationTemplateView,
    ShowTranslationTemplateView,
)
from cws2.views.user import EditUserView, ShowUserView

urlpatterns = [
    # admin
    path("admin/", admin.site.urls),
    # user
    path("@<str:user>", ShowUserView.as_view(), name="user.show"),
    path("profile", EditUserView.as_view(), name="user.edit"),
    # groups
    path("groups", IndexGroupView.as_view(), name="group.index"),
    path("groups/new", NewGroupView.as_view(), name="group.new"),
    path("groups/<slug:group>", ShowGroupView.as_view(), name="group.show"),
    path("groups/<slug:group>/edit", EditGroupView.as_view(), name="group.edit"),
    path("groups/<slug:group>/new", NewBoardView.as_view(), name="board.new"),
    # boards
    path("boards", IndexBoardView.as_view(), name="board.index"),
    path(
        "groups/<slug:group>/<slug:board>", ShowBoardView.as_view(), name="board.show"
    ),
    # messages
    path("messages", IndexMessageView.as_view(), name="message.index"),
    # language & dictionary
    path(
        "@<str:user>/<slug:language>", ShowLanguageView.as_view(), name="language.show"
    ),
    path(
        "@<str:user>/<slug:language>/edit",
        EditLanguageView.as_view(),
        name="language.edit",
    ),
    path(
        "@<str:user>/<slug:language>/dictionary",
        IndexWordView.as_view(),
        name="word.index",
    ),
    path(
        "@<str:user>/<slug:language>/dictionary/new",
        NewWordView.as_view(),
        name="word.new",
    ),
    path(
        "@<str:user>/<slug:language>/dictionary/<str:word>",
        ShowWordView.as_view(),
        name="word.show",
    ),
    path(
        "@<str:user>/<slug:language>/dictionary/<str:word>/edit",
        EditWordView.as_view(),
        name="word.edit",
    ),
    path("languages", IndexLanguageView.as_view(), name="language.index"),
    path("languages/new", NewLanguageView.as_view(), name="language.new"),
    # translations
    path(
        "translation", IndexTranslationTemplateView.as_view(), name="translation.index"
    ),
    path(
        "translation/new", NewTranslationTemplateView.as_view(), name="translation.new"
    ),
    path(
        "translation/<str:translation>",
        ShowTranslationTemplateView.as_view(),
        name="translation.show",
    ),
    # auth
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("register", CreateAccountView.as_view(), name="register"),
    # static
    path("about", AboutView.as_view(), name="about"),
    path("contact", ContactView.as_view(), name="contact"),
    path("donate", DonateView.as_view(), name="donate"),
    path("privacy", PrivacyView.as_view(), name="privacy"),
    # index
    path("", DashboardView.as_view(), name="dashboard"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG_TOOLBAR:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

cws2/models/dictionary.py
from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from shortuuid.django_fields import ShortUUIDField

from cws2.constants import PartOfSpeech, WordRegister
from cws2.models.base import TransientModel, TransientModelManager, UUIDModel
from cws2.utils.phonetics import ipa_from_ipa_or_xsampa


class WordClass(TransientModel):
    """
    Represents a specific word class that may be applied to a word in a user's
    language.
    """

    language = models.ForeignKey(
        "Language",
        on_delete=models.CASCADE,
        db_index=True,
        related_name="classes",
        verbose_name=_("Language"),
        help_text=_("The language to which this word class belongs."),
    )
    label = models.CharField(
        max_length=64,
        verbose_name=_("Label"),
        help_text=_(
            "The label for this word class, e.g. 'masculine' or 'imperfective'."
        ),
    )

    objects = TransientModelManager()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["language", "label"], name="cws2_wordclass_language_label"
            )
        ]

    def __str__(self):
        return f"{self.label} ({self.language.name})"


class Word(TransientModel, UUIDModel):
    """Represents a single word in a user's language."""

    uuid = ShortUUIDField(
        verbose_name=_("UUID"),
        max_length=22,
        length=22,
        unique=True,
        db_index=True,
        help_text=_("The unique ID that identifies this word."),
    )
    language = models.ForeignKey(
        "Language",
        on_delete=models.CASCADE,
        db_index=True,
        related_name="words",
        verbose_name=_("Language"),
        help_text=_("The language to which is this word belongs."),
    )
    dialect = models.ForeignKey(
        "Dialect",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        db_index=True,
        related_name="words",
        verbose_name=_("Dialect"),
        help_text=_(
            "If this word belongs to a specific dialect, you can set that here."
        ),
    )
    headword = models.CharField(
        max_length=255,
        db_index=True,
        verbose_name=_("Word"),
        help_text=_(
            "The word in your language. Double check you don't already have this word!"
        ),
    )
    alt_word = models.CharField(
        max_length=255,
        blank=True,
        verbose_name=_("Alternative word"),
        help_text=_(
            "An alternative written form of this word. Useful if your language uses "
            "more than one script."
        ),
    )
    ipa = models.CharField(
        max_length=255,
        blank=True,
        verbose_name=_("Pronunciation (IPA)"),
        help_text=_(
            "The pronunciation of this word in the International Phonetic Alphabet. "
            "Enter this as just IPA, without any enclosing brackets."
        ),
    )
    xsampa = models.CharField(
        max_length=255,
        blank=True,
        verbose_name=_("Pronunciation (X-SAMPA)"),
        help_text=_(
            "The pronunciation of this word in X-SAMPA. Enter this as just X-SAMPA, "
            "without any enclosing brackets."
        ),
    )
    source_language = models.CharField(
        max_length=128,
        blank=True,
        verbose_name=_("Source language"),
        help_text=_(
            "The language from which this word is derived or borrowed. Feel free to "
            "leave this blank, or use the 'etymology' field to give more detailed "
            "information."
        ),
    )
    etymology = models.TextField(
        blank=True,
        verbose_name=_("Etymology"),
        help_text=_("An optional explanation of how this word came to be."),
    )
    notes = models.TextField(
        blank=True,
        verbose_name=_("Notes"),
        help_text=_(
            "Any other notes that might be useful for understanding this dictionary "
            "entry."
        ),
    )
    reference_image = models.CharField(
        max_length=255,
        blank=True,
        verbose_name=_("Image link"),
        help_text=_(
            "The URL of a reference image that can be displayed with the word "
            "summary. Useful for conscripts and sign-languages."
        ),
    )
    roots = models.ManyToManyField(
        "Word",
        blank=True,
        verbose_name=_("Roots"),
        help_text=_("Any words from which this word derives."),
    )

    objects = TransientModelManager()

    def __str__(self):
        return f"{self.headword} ({self.language.name})"

    def get_absolute_url(self):
        return reverse(
            "word.show",
            kwargs={
                "user": self.language.created_by.username,
                "language": self.language.slug,
                "word": self.uuid,
            },
        )

    def get_edit_url(self):
        return reverse(
            "word.edit",
            kwargs={
                "user": self.language.created_by.username,
                "language": self.language.slug,
                "word": self.uuid,
            },
        )

    @cached_property
    def parts_of_speech(self):
        pos = {}
        for definition in self.definitions.all():
            if definition.part_of_speech not in pos:
                pos[definition.part_of_speech] = [definition]
            else:
                pos[definition.part_of_speech].append(definition)
        return pos

    @cached_property
    def pronunciation(self):
        return ipa_from_ipa_or_xsampa(self.ipa, self.xsampa)


class WordDefinition(TransientModel):
    """Represents a single definition for a word."""

    word = models.ForeignKey(
        "Word",
        on_delete=models.CASCADE,
        db_index=True,
        related_name="definitions",
        verbose_name=_("Word"),
        help_text=_("The word to which this definition belongs."),
    )
    part_of_speech = models.CharField(
        max_length=3,
        verbose_name=_("Part of speech"),
        choices=PartOfSpeech.CHOICES,
        help_text=_(
            "The part of speech for this definition of the word. If there's no exact "
            "match, just pick whichever is the closest."
        ),
    )
    register = models.CharField(
        max_length=4,
        blank=True,
        verbose_name=_("Register"),
        choices=WordRegister.CHOICES,
        help_text=_(
            "Here you can optionally specify the social register of this word, i.e. "
            "what specific context does this word belong to?"
        ),
    )
    definition = models.TextField(
        verbose_name=_("Definition"),
        help_text=_(
            "If possible, keep this as succinct as possible. You can always add extra "
            "definitions to this word."
        ),
    )
    classes = models.ManyToManyField(
        "WordClass",
        blank=True,
        verbose_name=_("Classes"),
        help_text=_(
            "Any classes to which this word belongs. If the classes have tables "
            "defined, these will be shown on the word's page."
        ),
    )

    objects = TransientModelManager()

    def __str__(self):
        return f"{self.word.headword}: {self.definition}"


class WordExample(TransientModel):
    definition = models.ForeignKey(
        "WordDefinition",
        on_delete=models.CASCADE,
        db_index=True,
        verbose_name=_("Definition"),
        help_text=_("The word definition to which this example belongs."),
    )
    text = models.TextField(
        verbose_name=_("Example text"),
        help_text=_("This is the example containing this sense of the word."),
    )
    translation = models.TextField(
        blank=True,
        verbose_name=_("Example translation"),
        help_text=_(
            "Optionally, you can put the English translation of the example here."
        ),
    )

    objects = TransientModelManager()

    def __str__(self):
        return self.text

cws2/forms/board.py
from django.forms import ModelForm

from cws2.models.board import Board


class BoardForm(ModelForm):
    class Meta:
        model = Board
        fields = ("name", "slug")

cws2/forms/group.py
from django.forms import ModelForm

from cws2.models.group import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = [
            "name",
            "slug",
            "icon",
            "icon_colour_bg",
            "icon_colour_fg",
            "access_type",
        ]

cws2/forms/widgets.py
from django.forms.widgets import ClearableFileInput


class ClearableImageInput(ClearableFileInput):
    template_name = "cws2/widgets/clearable_image_input.jinja"

cws2/views/base.py
from django.contrib import messages
from django.core.exceptions import ImproperlyConfigured
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views import generic


class View(generic.TemplateView):
    template_name = "cws2/base.jinja"
    body_colour = "green"

    available_themes = ["light", "dark"]
    theme_cookie_key = "theme"

    breadcrumb = ()
    breadcrumb_root = True

    page_title = None
    page_icon = None

    @property
    def breadcrumb_current(self):
        return self.page_title

    @property
    def theme(self):
        if (
            self.theme_cookie_key in self.request.COOKIES
            and self.request.COOKIES[self.theme_cookie_key] in self.available_themes
        ):
            return self.request.COOKIES[self.theme_cookie_key]
        return None

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            "body_colour": self.body_colour,
            "breadcrumb": self.breadcrumb,
            "breadcrumb_root": self.breadcrumb_root,
            "breadcrumb_current": self.breadcrumb_current,
            "page_title": self.page_title,
            "page_icon": self.page_icon,
            "theme": self.theme,
        }


class FormView(View, generic.FormView):
    template_name = "cws2/form.jinja"

    field_classes = {}
    field_prefixes = {}
    hidden_fields = {}
    form_data = {}

    @property
    def verb(self):
        return self.page_title

    @property
    def verb_icon(self):
        return self.page_icon or "bx-rocket"

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            "verb": self.verb,
            "verb_icon": self.verb_icon,
            "field_classes": self.field_classes,
            "field_prefixes": self.field_prefixes,
            "hidden_fields": self.hidden_fields,
            "form_data": self.form_data,
        }


class OwnableResourceMixin:
    """Contains useful functionality for views that deal with Ownable resources, such
    as automatically managing the permissions required to view the resource and
    automatically caching the resource as an attribute of the view.

    Example:
        ```
        class MyView(OwnableResourceView, FormView):
            ownable_permission_required = "write"

            def get_ownable_resource(self):
                return Resource.objects.get(slug=self.kwargs.get("resource"))
        ```
    """

    @property
    def ownable_permission_required(self):
        """The required permission needed on this Ownable resource to do what is being
        done in this view.

        Override this in child classes by setting `ownable_permission_required` as a
        class variable.

        Example:
            ```
            ownable_permission_required = "write"
            ```
        """
        raise ImproperlyConfigured(
            f"{self.__class__.__name__} inherits from OwnableMixin and must define "
            "ownable_permission_required."
        )

    @property
    def ownable_resource(self):
        """A cached copy of this view's ownable resource."""
        if not hasattr(self, "_ownable_resource") or not self._ownable_resource:
            self._ownable_resource = self.get_ownable_resource()
        return self._ownable_resource

    def get_ownable_resource(self):
        """A function used to fetch this view's ownable resource.

        Override this in child classes with the code required to fetch the ownable
        resource.

        Example:
            ```
            def get_ownable_resource(self):
                return Resource.objects.get(slug=self.kwargs.get("resource"))
            ```
        """
        raise ImproperlyConfigured(
            f"{self.__class__.__name__} inherits from OwnableMixin and must define "
            "get_ownable_resource()."
        )

    def handle_ownable_forbidden(self, request):
        """This function is called if the user does not have the required permissions
        to interact with this ownable resource.
        """
        if not self.request.user.is_authenticated:
            messages.warning(request, _("Try logging in before trying to access that!"))
            return HttpResponseRedirect(reverse("login"))
        if (
            self.ownable_permission_required != "read"
            and self.ownable_resource.is_public
        ):
            messages.warning(
                request, _("You don't have the required permissions to do that.")
            )
            return HttpResponseRedirect(self.ownable_resource.get_absolute_url())
        messages.warning(
            request, _("You don't have the required permissions to view that resource.")
        )
        return HttpResponseRedirect(reverse("dashboard"))

    def dispatch(self, request, *args, **kwargs):
        if not self.ownable_resource.check_user_permission(
            request.user, self.ownable_permission_required
        ):
            return self.handle_ownable_forbidden(request)
        return super().dispatch(request, *args, **kwargs)

cws2/templates/cws2/dictionary/edit.jinja
{% extends "cws2/form.jinja" %}
{% from "cws2/macros/field.jinja" import form_field %}

{% block form_content %}
    <div class="form__section">
        <h2 class="form__section-header"><i class="bx bx-pencil"></i> {% trans %}Entry{% endtrans %}</h2>
        <p class="form__section-text">
            {% trans %}This is the most basic information about this dictionary entry.{% endtrans %}
        </p>
    </div>
    {{ form_field(form.headword) }}
    {{ form_field(form.alt_word) }}
    {{ form_field(form.ipa) }}
    {{ form_field(form.xsampa) }}
    <div class="form__section form__section--separator">
        <h2 class="form__section-header"><i class="bx bx-leaf"></i> {% trans %}Notes & Etymology{% endtrans %}</h2>
        <p class="form__section-text">
            {% trans %}You can add supplementary notes and etymological information to this entry here.{% endtrans %}
        </p>
    </div>
    {{ form_field(form.etymology) }}
    {{ form_field(form.notes) }}
    {{ form_field(form.source_language) }}
    {{ form_field(form.reference_image) }}
{% endblock form_content %}

cws2/templates/cws2/dictionary/index.jinja
{% extends "cws2/base.jinja" %}

{% block page_actions %}
{% if request.user.is_authenticated and language.check_user_permission(request.user, "write") %}
<a href="{{ url('word.new', user=language.created_by.username, language=language.slug) }}" class="button button--accent">
    <i class="bx bx-message-alt-add"></i>
    {% trans %}New word{% endtrans %}
</a>
{% endif %}
{% endblock page_actions %}

{% block page_content %}
    <ul class="flex-list">
        <li class="flex-list__row flex-list__row--header">
            <span class="flex-list__column" style="flex-basis:34%">Headword</span>
            <span class="flex-list__column" style="flex-basis:66%">...</span>
        </li>
        {% for word in words %}
            <li class="flex-list__row">
                <span class="flex-list__column" style="flex-basis:34%">
                    <a href="{{ word.get_absolute_url() }}">{{ word.headword }}</a>
                </span>
                <span class="flex-list__column" style="flex-basis:66%">...</span>
            </li>
        {% endfor %}
    </ul>
{% endblock page_content %}

cws2/templates/cws2/dictionary/new.jinja
{% extends "cws2/form.jinja" %}
{% from "cws2/macros/field.jinja" import form_field %}

{% block form_content %}
    <div class="form__section">
        <h2 class="form__section-header"><i class="bx bx-pencil"></i> {% trans %}Entry{% endtrans %}</h2>
        <p class="form__section-text">
            {% trans %}This is the most basic information about this dictionary entry.{% endtrans %}
        </p>
    </div>
    {{ form_field(form.headword) }}
    {{ form_field(form.alt_word) }}
    {{ form_field(form.ipa) }}
    {{ form_field(form.xsampa) }}
    <div class="form__section form__section--separator">
        <h2 class="form__section-header"><i class="bx bx-message-square-dots"></i> {% trans %}Definition{% endtrans %}</h2>
        <p class="form__section-text">
            {% trans %}This is the first definition for this entry, which goes with a part of speech and optionally classes and a register. You'll be able to add more definitions to this entry later.{% endtrans %}
        </p>
    </div>
    {{ form_field(form.part_of_speech) }}
    {{ form_field(form.definition) }}
    {{ form_field(form.classes) }}
    {{ form_field(form.register) }}
    <div class="form__section form__section--separator">
        <h2 class="form__section-header"><i class="bx bx-leaf"></i> {% trans %}Notes & Etymology{% endtrans %}</h2>
        <p class="form__section-text">
            {% trans %}You can add supplementary notes and etymological information to this entry here.{% endtrans %}
        </p>
    </div>
    {{ form_field(form.etymology) }}
    {{ form_field(form.notes) }}
    {{ form_field(form.source_language) }}
    {{ form_field(form.reference_image) }}
{% endblock form_content %}

cws2/templates/cws2/dictionary/show.jinja
{% extends "cws2/base.jinja" %}

{% block breadcrumb_nav %}
    <div class="page__breadcrumb">
        <dl class="pre-dictionary">
            {% if word.alt_word %}
                <div class="pre-dictionary__entry">
                    <dt class="pre-dictionary__key" title="{% trans %}Alternative word{% endtrans %}">
                        <i class="bx bx-text"></i>
                        <span class="--sr-only">{% trans %}Alternative word{% endtrans %}</span>
                    </dt>
                    <dd class="pre-dictionary__value">{{ word.alt_word }}</dd>
                </div>
            {% endif %}
            {% if word.pronunciation %}
                <div class="pre-dictionary__entry">
                    <dt class="pre-dictionary__key" title="{% trans %}Pronunciation{% endtrans %}">
                        <i class="bx bx-volume-full"></i>
                        <span class="--sr-only">{% trans %}Pronunciation{% endtrans %}</span>
                    </dt>
                    <dd class="pre-dictionary__value">
                        <span class="--subtle --no-select">/</span>{{ word.pronunciation }}<span class="--subtle --no-select">/</span>
                    </dd>
                </div>
            {% endif %}
            <div class="pre-dictionary__entry">
                <dt class="pre-dictionary__key" title="{% trans %}Language{% endtrans %}">
                    {% if word.language.language_flag %}
                        <img
                            src="{{ word.language.language_flag.url }}"
                            alt="{% with language_name=language.name %}{% trans %}{{ language_name }}'s flag{% endtrans %}{% endwith %}"
                            class="flag flag--sm"
                        >
                    {% else %}
                        <i class="bx bx-message"></i>
                    {% endif %}
                    <span class="--sr-only">{% trans %}Language{% endtrans %}</span>
                </dt>
                <dd class="pre-dictionary__value">
                    <a href="{{ word.language.get_absolute_url() }}">{{ word.language.name }}</a>
                </dd>
            </div>
        </dl>
    </div>
{% endblock breadcrumb_nav %}

{% block page_actions %}
    <a href="{{ url('word.index', user=word.language.created_by.username, language=word.language.slug) }}" class="button button--accent">
        <i class="bx bx-left-arrow-alt"></i>
        {% trans %}Dictionary{% endtrans %}
    </a>
    {% if editable %}
        <a href="{{ word.get_edit_url() }}" class="button button--accent">
            <i class="bx bx-edit-alt"></i>
            {% trans %}Edit word{% endtrans %}
        </a>
    {% endif %}
{% endblock page_actions %}

{% block page_content %}
    {% for definitions in word.parts_of_speech.values() %}
        <div class="content-heading">
            <h2 class="content-heading__title content-heading__title--large">
                <i class="bx bx-message-square-dots"></i>
                {{ definitions[0].get_part_of_speech_display() }}
            </h2>
        </div>
        <div class="content dictionary">
            <ol class="dictionary__list">
                {% for definition in definitions %}
                    <li class="dictionary__item">
                        {% if definition.register %}
                            <span class="dictionary__item-register">({{ definition.get_register_display() }})</span>
                        {% endif %}
                        <span class="dictionary__item_definition">{{ definition.definition }}</span>
                    </li>
                {% endfor %}
            </ol>
        </div>
    {% endfor %}

    {% if word.etymology or word.source_language %}
        <div class="content-heading">
            <h2 class="content-heading__title content-heading__title--subtle">
                <i class="bx bx-leaf"></i>
                {% trans %}Etymology{% endtrans %}
            </h2>
        </div>
        <div class="content content--grid">
            {% if word.etymology %}
                <p class="content__item content__item--wide">{{ word.etymology }}</p>
            {% endif %}
            {% if word.source_language %}
                <div class="content__item content__item--wide">
                    <dl class="info info--inline info--subtle info--small">
                        <dt class="info__key">{% trans %}Source language{% endtrans %}</dt>
                        <dd class="info__value">{{ word.source_language }}</dd>
                    </dl>
                </div>
            {% endif %}
        </div>
    {% endif %}

    {% if word.notes %}
        <div class="content-heading">
            <h2 class="content-heading__title content-heading__title--subtle">
                <i class="bx bx-note"></i>
                {% trans %}Notes{% endtrans %}
            </h2>
        </div>
        <div class="content">
            {{ word.notes }}
        </div>
    {% endif %}
{% endblock page_content %}